spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:quote-db
    driver-class-name: org.h2.Driver
    username: <tbd>
    password: <tbd>